default: &default
  adapter: postgresql
  encoding: utf-8
  database: docker_practice
  host: db
  pool: 5

development:
  <<: *default
  database: docker_practice_development

test:
  <<: *default
  database: docker_practice_test
