default: &default
  adapter: postgresql
  encoding: utf-8
  database: docker_practice
  host: db
  port: 5432
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: docker_practice_development

test:
  <<: *default
  database: docker_practice_test
